<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>plantOBS-REST</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>plant-rest [root aggregator]</name>

    <modules>
        <module>plantOBS</module>
        <module>plantrmq</module>
        <module>plants-grpc-contract</module>
    
        <module>grpc-robot-customise-client</module>
        <module>grpc-analytics-server</module>
        <module>plantREST</module>
        <module>audit-service</module>
        <module>notification-service</module>
    </modules>

    <properties>
        <spring-boot.version>4.0.3</spring-boot.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <!--
        # Собрать всё в правильном порядке
        .\mvnw install

        # Запустить demo-rest - контракт соберётся автоматически
        .\mvnw spring-boot:run -pl demo-rest -am

        # Собрать только контракт (если менял только его)
        .\mvnw install -pl books-api-contract
    -->

</project>